[versions]
# libraries
commonsIO = "2.21.0"
snakeyaml = "2.5"
junit = "6.0.2"
assertj = "3.27.7"
wiremock = "3.13.2"

# plugins
kotlin = "2.3.0"
kover = "0.9.4"
pluginPublish = "2.0.0"

[libraries]
commonsIO = { group = "commons-io", name = "commons-io", version.ref = "commonsIO" }
snakeyaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeyaml" }
jupiterMain = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
wiremock = { group = "org.wiremock", name = "wiremock", version.ref = "wiremock" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }

[bundles]
jupiter = ["jupiterMain", "jupiterParams"]
